@{
    PSDependOptions              = @{
        AddToPath  = $true
        Target     = 'output\RequiredModules'
        Parameters = @{
            Repository      = 'PSGallery'
            AllowPreRelease = $true
        }
    }

    InvokeBuild                  = 'latest'
    PSScriptAnalyzer             = 'latest'
    Pester                       = 'latest'
    Plaster                      = 'latest'
    ModuleBuilder                = 'latest'
    ChangelogManagement          = 'latest'
    Sampler                      = 'latest'
    'Sampler.GitHubTasks'        = 'latest'
    Datum                        = 'latest'
    'Datum.ProtectedData'        = 'latest'
    DscBuildHelpers              = 'latest'
    'DscResource.Test'           = 'latest'
    MarkdownLinkCheck            = 'latest'
    'DscResource.AnalyzerRules'  = 'latest'
    'DscResource.DocGenerator'   = 'latest'
    PowerShellForGitHub          = 'latest'
    PSDesiredStateConfiguration  = 'latest'

    #DSC Resources
    xPSDesiredStateConfiguration = '9.2.1'
    ComputerManagementDsc        = '10.0.0'
    NetworkingDsc                = '9.1.0'
    JeaDsc                       = '4.0.0-preview0005'
    XmlContentDsc                = '0.0.1'
    WebAdministrationDsc         = '4.2.1'
    SecurityPolicyDsc            = '2.10.0.0'
    StorageDsc                   = '6.0.1'
    Chocolatey                   = '0.10.4'
    ActiveDirectoryDsc           = '6.7.1'
    DFSDsc                       = '5.2.0'
    WdsDsc                       = '0.12.0'
    DhcpServerDsc                = '4.0.0'
    xDscDiagnostics              = '2.8.0'
    DnsServerDsc                 = '3.0.3'
    FailoverClusterDsc           = '2.2.0'
    GPRegistryPolicyDsc          = '1.3.1'
    AuditPolicyDsc               = '1.4.0.0'
    SharePointDSC                = '5.7.0'
    ExchangeDsc                  = '2.0.0'
    SqlServerDsc                 = '17.5.1'
    UpdateServicesDsc            = '1.3.0'
    xWindowsEventForwarding      = '1.0.0.0'
    OfficeOnlineServerDsc        = '1.5.0'
    xBitlocker                   = '1.4.0.0'
    ActiveDirectoryCSDsc         = '5.0.0'
    HyperVDsc                    = '4.0.0-preview0005'
    DSCR_PowerPlan               = '1.3.0'
    FileSystemDsc                = '1.1.1'
    PackageManagement            = '1.4.8.1'
    PowerShellGet                = '2.2.5'
    ConfigMgrCBDsc               = '4.0.0'
    MmaDsc                       = '1.3.0'
    CertificateDsc               = '6.0.0'
    xRobocopy                    = '2.0.0.0'
    VSTSAgent                    = '2.0.14'
    FileContentDsc               = '1.3.0.151'
    xRemoteDesktopSessionHost    = '3.0.0'
    cScom                        = '1.1.0'

}
