@{
    PSDependOptions              = @{
        AddToPath  = $true
        Target     = 'output\RequiredModules'
        Parameters = @{
            Repository      = 'PSGallery'
            AllowPreRelease = $true
        }
    }

    InvokeBuild                  = 'latest'
    PSScriptAnalyzer             = 'latest'
    Pester                       = 'latest'
    Plaster                      = 'latest'
    ModuleBuilder                = 'latest'
    ChangelogManagement          = 'latest'
    Sampler                      = 'latest'
    'Sampler.GitHubTasks'        = 'latest'
    Datum                        = 'latest'
    'Datum.ProtectedData'        = 'latest'
    DscBuildHelpers              = '0.3.0-preview0003'
    'DscResource.Test'           = 'latest'
    MarkdownLinkCheck            = 'latest'
    'DscResource.AnalyzerRules'  = 'latest'
    'DscResource.DocGenerator'   = 'latest'
    PowerShellForGitHub          = 'latest'
    #PSDesiredStateConfiguration  = 'latest'

    #DSC Resources
    xPSDesiredStateConfiguration = '9.1.0'
    ComputerManagementDsc        = '8.5.0'
    NetworkingDsc                = '9.0.0'
    JeaDsc                       = '4.0.0-preview0005'
    XmlContentDsc                = '0.0.1'
    WebAdministrationDsc         = '4.1.0'
    SecurityPolicyDsc            = '2.10.0.0'
    StorageDsc                   = '5.0.1'
    Chocolatey                   = '0.0.79'
    ActiveDirectoryDsc           = '6.2.0'
    DFSDsc                       = '5.0.1'
    WdsDsc                       = '0.11.0'
    xDhcpServer                  = '3.1.0'
    xDscDiagnostics              = '2.8.0'
    DnsServerDsc                 = '3.0.0'
    FailoverClusterDsc           = '2.1.0'
    GPRegistryPolicyDsc          = '1.2.0'
    AuditPolicyDsc               = '1.4.0.0'
    SharePointDSC                = '4.8.0'
    xExchange                    = '1.33.0'
    SqlServerDsc                 = '17.1.0'
    UpdateServicesDsc            = '1.2.1'
    xWindowsEventForwarding      = '1.0.0.0'
    OfficeOnlineServerDsc        = '1.5.0'
    xBitlocker                   = '1.4.0.0'
    ActiveDirectoryCSDsc         = '5.0.0'
    HyperVDsc                    = '4.0.0-preview0005'
    DSCR_PowerPlan               = '1.3.0'
    FileSystemDsc                = '1.1.1'
    PackageManagement            = '1.4.8.1'
    PowerShellGet                = '2.2.5'
    ConfigMgrCBDsc               = '3.0.0'
    MmaDsc                       = '1.3.0'
    CertificateDsc               = '6.0.0'
    xRobocopy                    = '2.0.0.0'
    VSTSAgent                    = '2.0.14'
    FileContentDsc               = '1.3.0.151'
    xRemoteDesktopSessionHost    = '3.0.0-preview0001'
    cScom                        = '1.0.5'

}
