// CommonTasks YAML Reference: DscTagging
// ======================================

:YmlCategory: DscTagging

:abstract:  {YmlCategory} contains information about the current DSC configuration (version, envrionment, modules, ...).

[#dscyml_dsctagging]
= DSC Resource '{YmlCategory}'


[[dscyml_dsctagging_abstract, {abstract}]]
{abstract}


[cols="1,3a" options="autowidth" caption=]
|===
| Source         | https://github.com/dsccommunity/CommonTasks/tree/main/source/DSCResources/DscTagging
| DSC Resource   | https://github.com/dsccommunity/xPSDesiredStateConfiguration[xPSDesiredStateConfiguration], 
                   https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/?view=powershell-7[PSDesiredStateConfiguration]
| Documentation  | https://github.com/dsccommunity/xPSDesiredStateConfiguration#xregistry[xRegistry]
|===

.Attributes of category '{YmlCategory}'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| Version
| Mandatory
| System.Version
| DSC configuration version
|

| Environment
| Mandatory
| String
| DSC environment information
|

| NodeVersion
| 
| System.Version
| Optional node specific DSC configuration version
|

| NodeRole
| 
| String
| Role of the node
|

| DisableGitCommitId
| 
| Boolean
| Disable export of git commit id
| - True
  - *False* (default)

| Layers
| 
| String[]
| List of used layers (YAML files) for each node
|

|===


[NOTE]
====
To fill the `Layers` list each YAML file requires an `DscTagging` configuration.
In these configuration the attribute `Layers` should be set with the current layer name (e.g. YAML file name).
In `Datum.yml` the merging rules for `DscTagging` must be specified as deep merge.
====


.Example `Datum.yml` (Excerpt)
[source, yaml]
----
ResolutionPrecedence:
  - AllNodes\$($Node.Environment)\$($Node.NodeName)
  - Environment\$($Node.Environment)
  - Roles\$($Node.Role)
  - Roles\ServerBaseline

lookup_options:
  # merge rules of DscTagging - using Add to identify duplicate module names
  DscTagging:
    merge_hash: deep
  DscTagging\Modules:
    merge_basetype_array: Add
----


.Example of `AllNodes\MyComputer.yml` (Excerpt)
[source, yaml]
----
NodeName:    MyComputer
Environment: Dev
Role:        FileServer
MyVersion:   1.1
----


.Example `Environment\Dev.yml` (Excerpt)
[source, yaml]
----
DscTagging:
  Environment: Dev
  # use Datum.InvokeCommand to get the role name and version of the current node
  NodeRole:    '[x={ $node.Role }=]'
  NodeVersion: '[x={ $node.MyVersion }=]'
  Layers:
    - Environment\Dev
----


.Example `Roles\FileServer.yml` (Excerpt)
[source, yaml]
----
DscTagging:
  Layers:
    - Roles\FileServer
----


.Example `Roles\ServerBaseline.yml` (Excerpt)
[source, yaml]
----
Configurations:
  - DscTagging
  
DscTagging:
  Version: 0.3.0
  Layers:
    - Roles\ServerBaseline
----


.Example of RSOP `MyComputer.yml` (Excerpt)
[source, yaml]
----
Configurations:
  - DscTagging
  
DscTagging:
  Version:     0.3.0
  Environment: Dev
  NodeRole:    FileServer
  NodeVersion: 1.1
  Layers:
    - Environment\Dev
    - Roles\FileServer
    - Roles\ServerBaseline
----