// CommonTasks YAML Reference: ExchangeMailboxDatabases
// ====================================================

:YmlCategory: ExchangeMailboxDatabases

:abstract:    {YmlCategory} creates and configures Exchange Server mailbox databases.

[#dscyml_exchangemailboxdatabases]
= DSC Resource '{YmlCategory}'

[[dscyml_exchangemailboxdatabases_abstract, {abstract}]]
{abstract}

.When to use '{YmlCategory}'
****
Use this resource when you need to create and configure mailbox databases on Exchange Server. Mailbox databases store user mailbox data and must be created before users can be provisioned. Configure database paths, quotas, and maintenance schedules as needed.
****


[cols="1,3a" options="autowidth" caption=]
|===
| Source         | https://github.com/dsccommunity/CommonTasks/tree/main/source/DSCResources/ExchangeMailboxDatabases
| DSC Resource   | https://github.com/dsccommunity/ExchangeDsc[ExchangeDsc]
| Documentation  |
|===


.Attributes of category '{YmlCategory}'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| Items
| Mandatory
| Hashtable[]
| List of mailbox database configurations
|

|===


.Example
[source, yaml]
----
ExchangeMailboxDatabases:
    Items:
    - Name: DAG01-DB1
        Credential: '[ENC=PE9ianMgVmVy...=]'
        EdbFilePath: C:\ExchangeDatabases\DAG01-DB1\DAG01-DB1.db\DAG01-DB1.edb
        LogFolderPath: C:\ExchangeDatabases\DAG01-DB1\DAG01-DB1.log
        CircularLoggingEnabled: true
        DatabaseCopyCount: 4
        IssueWarningQuota: 50176MB
        ProhibitSendQuota: 51200MB
        ProhibitSendReceiveQuota: 52224MB
        AllowServiceRestart: true
    - Name: DAG02-DB1
        Credential: '[ENC=PE9ianMgVmVyc...=]'
        EdbFilePath: C:\ExchangeDatabases\DAG02-DB1\DAG02-DB1.db\DAG01-DB1.edb
        LogFolderPath: C:\ExchangeDatabases\DAG02-DB1\DAG02-DB1.log
        CircularLoggingEnabled: true
        DatabaseCopyCount: 4
        IssueWarningQuota: 50176MB
        ProhibitSendQuota: 51200MB
        ProhibitSendReceiveQuota: 52224MB
        AllowServiceRestart: true
----

.See also
****
* xref:exchangeprovisioning.adoc[ExchangeProvisioning]
* xref:exchangeconfiguration.adoc[ExchangeConfiguration]
* xref:exchangeautomountpoints.adoc[ExchangeAutoMountPoints]
* xref:exchangemailboxdatabasecopies.adoc[ExchangeMailboxDatabaseCopies]
* xref:exchangedagprovisioning.adoc[ExchangeDagProvisioning]
****
