// CommonTasks YAML Reference: ScomSettings
// ========================================

:YmlCategory: ScomSettings

:abstract:    {YmlCategory} configures SCOM operational settings including alert resolution, heartbeat, database grooming, data warehouse, error reporting, and web addresses.

[#dscyml_scomsettings]
= DSC Resource '{YmlCategory}'

[[dscyml_scomsettings_abstract, {abstract}]]
{abstract}

.When to use '{YmlCategory}'
****
Use this resource when you need to configure the operational behavior of your SCOM management group. It manages settings for approval policies, alert resolution timing, database grooming schedules, data warehouse configuration, error reporting, heartbeat intervals, reporting server URLs, and web console addresses.
****


[cols="1,3a" options="autowidth" caption=]
|===
| Source         | https://github.com/dsccommunity/CommonTasks/tree/main/source/DSCResources/ScomSettings
| DSC Resource   | https://github.com/nyanhp/cScom[cScom]
| Documentation  |

|===


.Attributes of category '{YmlCategory}'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| ApprovalSetting
|
| string
| SCOM agent approval policy setting.
| - Pending
- AutoReject
- AutoApprove

| AlertResolutionSetting
|
| Hashtable
| SCOM alert resolution timing configuration.
|

| DatabaseGroomingSetting
|
| Hashtable
| SCOM database grooming schedule configuration.
|

| DataWarehouseSetting
|
| Hashtable
| SCOM data warehouse configuration.
|

| ErrorReportSetting
|
| string
| SCOM error reporting behavior setting.
| - AutomaticallySend
- OptOut
- PromptBeforeSending

| HeartbeatSetting
|
| Hashtable
| SCOM heartbeat interval configuration.
|

| ReportingServerUrl
|
| string
| URL of the SCOM reporting server.
|

| WebAddressSetting
|
| Hashtable
| SCOM web console address configuration.
|

|===


.Example
[source, yaml]
----
ScomSettings:
  ApprovalSetting: AutoApprove
  AlertResolutionSetting:
    AlertAutoResolveDays: 4
    HealthyAlertAutoResolveDays: 1
  DatabaseGroomingSetting:
    AlertDaysToKeep: 7
    AvailabilityHistoryDaysToKeep: 7
    EventDaysToKeep: 7
    JobStatusDaysToKeep: 7
    MaintenanceModeHistoryDaysToKeep: 7
    MonitoringJobDaysToKeep: 7
    PerformanceDataDaysToKeep: 7
    PerformanceSignatureDaysToKeep: 7
    StateChangeEventDaysToKeep: 7
  DataWarehouseSetting:
    DatabaseName: SCOM2019
    ServerName: SCBD1\SomeInstance
  ErrorReportSetting: OptOut
  HeartbeatSetting:
    MissingHeartbeatThreshold: 10
    HeartbeatIntervalSeconds: 60
  ReportingServerUrl: http://SCRS1:80/ReportServer
  WebAddressSetting:
    WebConsoleUrl: http://OM01.contoso.com/OperationsManager
    OnlineProductKnowledgeUrl: http://OM01.contoso.com/Knowledge
----
