// CommonTasks YAML Reference: SqlPermissions
// ==========================================

:YmlCategory: SqlPermissions

:abstract:    {YmlCategory} grants, denies, or revokes server-level permissions for SQL Server logins.

[#dscyml_sqlpermissions]
= DSC Resource '{YmlCategory}'

[[dscyml_sqlpermissions_abstract, {abstract}]]
{abstract}

.When to use '{YmlCategory}'
****
Use this resource when you need to manage server-level permissions for SQL Server logins, such as granting CONNECT SQL, ALTER ANY DATABASE, VIEW SERVER STATE, or other server-scoped permissions. Create the logins first with SqlLogins.
****
For more information about permissions, please read the article https://docs.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine[Permissions (Database Engine)].

[NOTE]
====
When revoking permission with PermissionState `GrantWithGrant`, both the grantee and all the other users the grantee has granted the same permission to, will also get their permission revoked.
====


// reference links as variables for using more than once
:ref_sqlserverdsc_wiki:            https://github.com/dsccommunity/SqlServerDsc/wiki[SqlServerDsc Wiki]
:ref_sqlserverdsc_sqlpermission:   https://github.com/dsccommunity/SqlServerDsc/wiki/SqlPermission[SqlPermission]


[cols="1,3a" options="autowidth" caption=]
|===
| Source         | https://github.com/dsccommunity/CommonTasks/tree/main/source/DSCResources/SqlPermissions
| DSC Resource   | https://github.com/dsccommunity/SqlServerDsc[SqlServerDsc]
| Documentation  | - {ref_sqlserverdsc_wiki}
                   - {ref_sqlserverdsc_sqlpermission}
                   
|===


.Requirements

- Target machine must be running Windows Server 2012 or later.
- Target machine must be running SQL Server Database Engine 2012 or later.
- Target machine must have access to the SQLPS PowerShell module or the SqlServer PowerShell module.


.Attributes of category '{YmlCategory}'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| [[dscyml_sqlpermissions_values, {YmlCategory}/Values]]<<dscyml_sqlpermissions_values_details, Values>>
| Mandatory
| Hashtable[]
| List of SQL permissions.
|

|===


[[dscyml_sqlpermissions_values_details]]
.Attributes of category '<<dscyml_sqlpermissions_values>>'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| InstanceName
| Key
| String
| The name of the SQL Server instance to be configured.
|

| ServerName
|
| String
| The host name of the SQL Server to be configured.

Default value is the current computer name.
|

| Enure
|
| String
| Determines whether the alias should be added (`Present`) or removed (`Absent`).
| - *Present* (default)
  - Absent

| Principal
| Key
| String
| The login to which permission will be set.
|

| [[dscyml_sqlpermissions_permission, {YmlCategory}/Values/Permission]]<<dscyml_sqlpermissions_permission_details, Permission>>
| Mandatory
| Hashtable[]
| The permission to set for the login.
|

|===


[[dscyml_sqlpermissions_permission_details]]
.Attributes of category '<<dscyml_sqlpermissions_permission>>'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| Grant
|
| String[]
| Permission state `Grant`

All valid permission names can be found in the article https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.serverpermissionset#properties[ServerPermissionSet Class properties].
| - ConnectSql
  - AlterAnyAvailabilityGroup
  - ViewServerState
  - AlterAnyEndPoint
  - ...

| GrantWithGrant
|
| String[]
| Permission state `GrantWithGrant`

When revoking permission with PermissionState `GrantWithGrant`, both the grantee and all the other users the grantee has granted the same permission to, will also get their permission revoked.

All valid permission names can be found in the article https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.serverpermissionset#properties[ServerPermissionSet Class properties].
| - ConnectSql
  - AlterAnyAvailabilityGroup
  - ViewServerState
  - AlterAnyEndPoint
  - ...

| Deny
|
| String[]
| Permission state `Deny`

All valid permission names can be found in the article https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.serverpermissionset#properties[ServerPermissionSet Class properties].
| - ConnectSql
  - AlterAnyAvailabilityGroup
  - ViewServerState
  - AlterAnyEndPoint
  - ...

|===


.Example
[source, yaml]
----
SqlPermissions:
  Values:
    - Name: NT SERVICE\ClusSvc$
      InstanceName: MSSQLSERVER
      Permission:
        Grant:
          - AlterAnyAvailabilityGroup
          - ViewServerState
          - ConnectSql
        GrantWithGrant:
          - ViewServerState
          - ConnectSql
    - Name: contoso\dbadmin
      InstanceName: MSSQLSERVER
      ServerName: localhost
      Permission:
        Grant:
          - AlterAnyEndPoint
        GrantWithGrant:
          - ViewServerState
          - ConnectSql
        Deny:
          - AlterAnyAvailabilityGroup
      PermissionToInclude:
        Grant:
          - AlterAnyEndPoint
        GrantWithGrant:
          - ViewServerState
          - ConnectSql
        Deny:
          - AlterAnyAvailabilityGroup
      PermissionToExclude:
        Grant:
          - AlterAnyEndPoint
        GrantWithGrant:
          - ViewServerState
          - ConnectSql
        Deny:
          - AlterAnyAvailabilityGroup
----
