// CommonTasks YAML Reference: WebSites
// ========================================

:YmlCategory: WebSites


[[dscyml_websites, {YmlCategory}]]
= DSC Resource 'WebSites'
// didn't work in production: = DSC Resource '{YmlCategory}'


[[dscyml_websites_abstract]]
.{YmlCategory} module is used to manage ISS web sites.


[cols="1,3a" options="autowidth" caption=]
|===
| Source         | https://github.com/dsccommunity/CommonTasks/tree/main/source/DSCResources/WebSites
| DSC Resource   | https://github.com/dsccommunity/xWebAdministration[xWebAdministration]
| Documentation  | https://github.com/dsccommunity/xWebAdministration#xwebsite[xWebSite]
|===


.Attributes of category '{YmlCategory}'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| [[dscyml_websites_items, {YmlCategory}/Items]]<<dscyml_websites_items_details, Items>>
|
| Hashtable[]
| IIS Web Sites
|

|===


[[dscyml_websites_items_details]]
.Attributes of category '<<dscyml_websites_items>>'
[cols="1,1,1,2a,1a" options="header"]
|===
| Parameter
| Attribute
| DataType
| Description
| Allowed Values

| Name
| Key
| String
| The desired name of the website.
|

| SiteId
|
| UInt32 
| Optional. The desired IIS site Id for the website.
|

| PhysicalPath
|
| String
| The path to the files that compose the website.
|

| State
|
| String
| The state of the website
| - Started
  - Stopped

| BindingInfo
|
| Hashtable[]
| Website's binding information in the form of an array of embedded instances of the MSFT_xWebBindingInformation CIM class that implements the following properties:

  - *Protocol*: The protocol of the binding. This property is required. The acceptable values for this property are: http, https, msmq.formatname, net.msmq, net.pipe, net.tcp.

  - *BindingInformation*: The binding information in the form a colon-delimited string that includes the IP address, port, and host name of the binding. This property is ignored for http and https bindings if at least one of the following properties is specified: IPAddress, Port, HostName.
  
  - *IPAddress*: The IP address of the binding. This property is only applicable for http and https bindings. The default value is *.

  - *Port*: The port of the binding. The value must be a positive integer between 1 and 65535. This property is only applicable for http (the default value is 80) and https (the default value is 443) bindings.

  - *HostName*: The host name of the binding. This property is only applicable for http and https bindings.

  - *CertificateThumbprint*: The thumbprint of the certificate. This property is only applicable for https bindings.

  - *CertificateSubject*: The subject of the certificate if the thumbprint isn't known. This property is only applicable for https bindings.

  - *CertificateStoreName*: The name of the certificate store where the certificate is located. This property is only applicable for https bindings. The acceptable values for this property are: My, WebHosting. The default value is My.

  - *SslFlags*: The type of binding used for Secure Sockets Layer (SSL) certificates. This property is supported in IIS 8.0 or later, and is only applicable for https bindings. The acceptable values for this property are:
    
    * 0: The default value. The secure connection be made using an IP/Port combination. Only one certificate can be bound to a combination of IP address and the port.
    * 1: The secure connection be made using the port number and the host name obtained by using Server Name Indication (SNI). It allows multiple secure websites with different certificates to use the same IP address.
    * 2: The secure connection be made using the Centralized Certificate Store without requiring a Server Name Indication.
    * 3: The secure connection be made using the Centralized Certificate Store while requiring Server Name Indication.
|

| ApplicationPool
|
| String
| The name of the website’s application pool.
|

| DefaultPage
|
| String[]
| One or more names of files that will be set as Default Documents for this website.
|

| EnabledProtocols
|
| String
| The protocols that are enabled for the website.
|

| ServerAutoStart
|
| Boolean
| When set to $true this will enable Autostart on a Website
| - True
  - False

| Ensure
|
| String
| Ensures that the website is Present or Absent.
| - *Present* (default)
  - Absent

| PreloadEnabled
|
| Boolean
| When set to `True` this will allow WebSite to automatically start without a request
| - True
  - False

| ServiceAutoStartEnabled
|
| Boolean
| When set to `True` this will enable application Autostart (application initalization without an initial request) on a Website
| - True
  - False

| ServiceAutoStartProvider
|
| String
| Adds a AutostartProvider
|

| ApplicationType
|
| String
| Adds a AutostartProvider ApplicationType
|

| AuthenticationInfo
|
| Hashtable
| Website's authentication information in the form of an embedded instance of the MSFT_xWebAuthenticationInformation CIM class.
  MSFT_xWebAuthenticationInformation takes the following properties:

  - *Anonymous*: The acceptable values for this property are: $true, $false
  - *Basic* The acceptable values for this property are: $true, $false
  - *Digest*: The acceptable values for this property are: $true, $false
  - *Windows*: The acceptable values for this property are: $true, $false
|

| LogPath
|
|
| The directory to be used for logfiles.
|

| LogFlags
|
|
| The W3C logging fields

The values that are allowed for this property are: Date,Time,ClientIP,UserName,SiteName,ComputerName,ServerIP,Method,UriStem,UriQuery,HttpStatus,Win32Status,BytesSent,BytesRecv,TimeTaken,ServerPort,UserAgent,Cookie,Referer,ProtocolVersion,Host,HttpSubStatus
|

| LogPeriod
|
|
| How often the log file should rollover.

The values that are allowed for this property are: Hourly,Daily,Weekly,Monthly,MaxSize
|

| LogTargetW3C
|
|
| Log Target of the W3C Logfiles.
| - File
  - ETW
  - File,ETW

| LogTruncateSize
|
|
| How large the file should be before it is truncated.

If this is set then LogPeriod will be ignored if passed in and set to MaxSize. 
The value must be a valid integer between 1048576 (1MB) and 4294967295 (4GB).
| 1MB - 4GB

| LoglocalTimeRollover
|
| Boolean
| Use the localtime for file naming and rollover.
| - True
  - False

| LogFormat
|
|
| Format of the Logfiles.

NOTE: Only `W3C` supports `LogFlags`.
| - IIS
  - W3C
  - NCSA

| LogCustomFields
|
| Hashtable[]
| Custom logging field information the form of an array of embedded instances of the MSFT_xLogCustomFieldInformation CIM class that implements the following properties:

  - *LogFieldName*: Field name to identify the custom field within the log file. Please note that the field name cannot contain spaces.
  - *SourceType*: The acceptable values for this property are: RequestHeader, ResponseHeader, or ServerVariable (note that enhanced logging cannot log a server variable with a name that contains lower-case characters - to include a server variable in the event log just make sure that its name consists of all upper-case characters).
  - *SourceName*: Name of the HTTP header or server variable (depending on the Source Type you selected) that contains a value that you want to log.

|===


.Example
[source, yaml]
----
WebSites:
  Items:
    # Remove Default WebSite
    - Name: Default Web Site
      Ensure: Absent
    # Create New WebSite
    - Name: TestSite2
      ApplicationPool: TestAppPool2
      AuthenticationInfo:
        Anonymous: False
        Basic:     True
        Digest:    False
        Windows:   True
----